name: Trigger auto deployment for containerapps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:


  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Deploy to workerapp
        uses: azure/CLI@v1
        with:
          azcliversion: 2.20.0
          inlineScript: |
            echo "Installing workerapp extension"
            az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/workerapp-0.1.3-py2.py3-none-any.whl --yes
            echo "Starting Deploying"
            az workerapp update -n myapp -g workerapps-rg-xj -i nginx:latest --target-port 80
