name: Trigger auto deployment for cont-acr

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/cont-acr-AutoDeployTrigger-4986a645-b76d-45ae-83b9-c5ee89657654.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: antuxtest.azurecr.io
          username: ${{ secrets.CONTACR_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTACR_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: antuxtest.azurecr.io/container-deploy:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTACR_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cont-acr -g OGFS194-0808-gayathri --server antuxtest.azurecr.io --username  ${{ secrets.CONTACR_REGISTRY_USERNAME }} --password ${{ secrets.CONTACR_REGISTRY_PASSWORD }}
            az containerapp update -n cont-acr -g OGFS194-0808-gayathri --image antuxtest.azurecr.io/container-deploy:${{ github.sha }}
